# Generated by Django 4.0.7 on 2022-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_comment_published_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.CharField(default='dssdsfsdfsdfsdfsdfsdfsdfsd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(default='None', upload_to='static/images', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
