# Generated by Django 4.0.7 on 2022-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_quote_description_quote_image_alter_quote_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images', verbose_name='image'),
        ),
    ]
